name: Build and Deploy AI Agents Laboratory

env:
    API_PROJECT_PATH: AIAgents.Laboratory.API/AIAgents.Laboratory.API.csproj
    UI_PROJECT_PATH: AIAgents.Laboratory.UI
    DATABASE_PROJECT_PATH: AIAgents.Laboratory.Database/AIAgents.Laboratory.Database.sqlproj

on:
    workflow_dispatch:
        inputs:
            deploy_api:
                description: "AIAgents.Laboratory.API"
                required: true
                default: true
                type: boolean

            deploy_ui:
                description: "AIAgents.Laboratory.UI"
                required: false
                default: true
                type: boolean

            deploy_db:
                description: "AIAgents.Laboratory.Database"
                required: false
                default: true
                type: boolean

jobs:
    build-api:
        name: Build AIAgents.Laboratory.API
        runs-on: ubuntu-latest
        if: ${{ inputs.deploy_api }}
        outputs:
            artifact_path: ${{ steps.set-artifact-path.outputs.path }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 10.0.x

            - name: Install dependencies and build solution
              run: |
                  dotnet restore ${{ env.API_PROJECT_PATH }}
                  dotnet build ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore

            - name: Publish the API project
              run: |
                  dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-build --output ./publish-api

            - name: Set artifact path
              id: set-artifact-path
              run: echo "path=./publish-api" >> $GITHUB_OUTPUT

            - name: Upload API artifact
              uses: actions/upload-artifact@v4
              with:
                  name: api-artifact
                  path: ./publish-api

    deploy-api:
        name: Deploy AIAgents.Laboratory.API
        runs-on: ubuntu-latest
        needs: build-api
        environment: Production
        steps:
            - name: Download API artifacts
              uses: actions/download-artifact@v4
              with:
                  name: api-artifact
                  path: ./publish-api

            - name: Deploy to Azure App Service
              uses: Azure/webapps-deploy@v2
              with:
                  app-name: app-webapi-ai-agents-lab
                  slot-name: production
                  publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
                  package: ./publish-api

    build-and-deploy-web:
        name: Build and Deploy AIAgents.Laboratory.UI
        if: ${{ inputs.deploy_ui }}
        runs-on: ubuntu-latest
        environment: Production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies and build UI
              run: |
                  cd ${{ env.UI_PROJECT_PATH }}
                  npm install
                  npm run build

            - name: Deploy UI to Azure Web App
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
                  action: "upload"
                  app_location: ${{ env.UI_PROJECT_PATH }}
                  output_location: "out"

    build-database:
        name: Build AIAgents.Laboratory.Database
        runs-on: windows-latest
        if: ${{ inputs.deploy_db }}
        outputs:
            artifact_path: ${{ steps.set-artifact-path.outputs.path }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET 10
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "10.0.x"

            - name: Install dependencies and build DB solution
              run: |
                  dotnet restore ${{ env.DATABASE_PROJECT_PATH }}
                  dotnet build ${{ env.DATABASE_PROJECT_PATH }} --configuration Release --no-restore

            - name: Publish the dacpac file
              run: |
                  dotnet publish ${{ env.DATABASE_PROJECT_PATH }} --configuration Release --output ./publish-db

            - name: Set datbase objects artifact path
              id: set-artifact-path
              run: echo "path=./publish-db" >> $GITHUB_OUTPUT

            - name: Upload Database Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: db-artifact
                  path: ./publish-db

    deploy-database:
        name: Deploy AIAgents.Laboratory.Database
        runs-on: windows-latest
        needs: build-database
        environment: Production
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Download database artifact
              uses: actions/download-artifact@v4
              with:
                  name: db-artifact
                  path: ./publish-db

            - name: Deploy to Azure SQL Database
              uses: azure/sql-action@v2.3
              with:
                  connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
                  path: "./publish-db/AIAgents.Laboratory.Database.dacpac"
                  action: "publish"
                  arguments: "/p:DropObjectsNotInSource=true /p:BlockOnPossibleDataLoss=false /p:IgnoreUserSettingsObjects=true /p:IgnoreLoginSids=true /p:IgnorePermissions=true /p:IgnoreRoleMembership=true"
